dist: bionic

language: ruby
cache: bundler

if: tag IS blank

env:
  - TEST_GROUP="cucumber features/other_a"

services:
  - mysql
  - redis
  - memcached

before_install:
  - bash script/travis/ebook_converters.sh

before_script:
  - bash script/travis/configure.sh
  - bash script/travis/elasticsearch_upgrade.sh
  - bash script/travis/multiple_redis.sh
  - bash script/travis/mysql.sh

script:
  - export RAILS_ENV=test
  - export CUCUMBER_FORMAT=Ao3Cucumber::Formatter
  - export CUCUMBER_RETRY=1
  - bundle exec rake db:schema:load
  - bundle exec rake db:migrate
  - bundle exec "$TEST_GROUP"

after_failure:
  - tail -v -n +1 $TRAVIS_BUILD_DIR/tmp/capybara/*.html
