language: ruby
dist: trusty
cache:
  bundler: true
  directories:
  - features/cassette_library
sudo: required
env:
  - TEST_GROUP="./script/check_syntax"
  - TEST_GROUP="rspec spec"
  - TEST_GROUP="cucumber -r features features/importing          -f Ao3Cucumber::Formatter --color"
rvm:
  - "2.2.5"
services:
  - elasticsearch
  - redis-server
  - memcached
script:
  - RAILS_ENV=test bundle exec rake db:schema:load --trace
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec $TEST_GROUP
before_script:
  - bash script/travis_configure.sh
  - bash script/travis_elasticsearch_upgrade.sh
  - bash script/travis_multiple_redis.sh
