sudo: required
dist: xenial

language: ruby
cache: bundler

if: tag IS blank

env:
  - TEST_GROUP="./script/check_syntax"

services:
  - mysql
  - redis
  - memcached

before_install:
  - bash script/travis_ebook_converters.sh

before_script:
  - bash script/travis_configure.sh
  - bash script/travis_elasticsearch_upgrade.sh
  - bash script/travis_multiple_redis.sh
  - bash script/travis_mysql.sh

script:
  - RAILS_ENV=test bundle exec rake db:schema:load --trace
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec $TEST_GROUP

after_failure:
  - tail -v -n +1 $TRAVIS_BUILD_DIR/tmp/capybara/*.html
