name: Run tests with Docker

on:
  push:
    branches: ['**']
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: ./script/docker/init.sh
